-- Rentals: brings the old Rental-Manager app (cfritzlen/Rental-Manager)
-- into this project. Run once in Supabase → SQL Editor. Idempotent.
--
-- Tables are prefixed rental_ to avoid clashing with the homestead tables.
-- After running this, open rentals.html → Import tab to copy the data over
-- from the old project (browser does the copy; ids are preserved so the
-- payment ↔ default ↔ rate-schedule links survive).

-- Master list of units/buildings
create table if not exists public.rental_properties (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    property_name text not null,
    building text,
    is_building_level boolean default false,
    status text default 'active'
);

-- Leases (matches the old app's form: up to 4 tenants per lease)
create table if not exists public.rental_leases (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    tenant_names text,
    tenant_count text,
    tenant1_name text, tenant1_email text, tenant1_phone text, tenant1_employer text,
    tenant2_name text, tenant2_email text, tenant2_phone text, tenant2_employer text,
    tenant3_name text, tenant3_email text, tenant3_phone text, tenant3_employer text,
    tenant4_name text, tenant4_email text, tenant4_phone text, tenant4_employer text,
    property_address text not null,
    lease_start date not null,
    lease_end date not null,
    lease_type text not null,          -- month_to_month, 12_month, 24_month
    lease_months text,
    base_rent numeric(10,2),
    rent_amount numeric(10,2) not null,
    security_deposit numeric(10,2),
    first_month_rent numeric(10,2),
    last_month_rent numeric(10,2),
    num_cats integer default 0,
    cat_fee numeric(10,2) default 0,
    num_dogs integer default 0,
    dog_fee numeric(10,2) default 0,
    notes text,
    status text default 'active'       -- active, expired, terminated
);
create index if not exists idx_rental_leases_property on public.rental_leases(property_address);
create index if not exists idx_rental_leases_status on public.rental_leases(status);

-- Recurring things that get paid monthly (rent expected per unit, mortgages)
create table if not exists public.rental_payment_defaults (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    type text not null,                -- rent | mortgage
    label text not null,
    property_name text,
    default_amount numeric(10,2) not null,
    due_day integer,
    status text default 'active'
);

-- What actually got paid, per month ("period" is YYYY-MM)
create table if not exists public.rental_payments (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    payment_default_id bigint references public.rental_payment_defaults(id) on delete cascade,
    period text not null,
    amount_owed numeric(10,2),
    amount_paid numeric(10,2),
    date_paid date
);
create index if not exists idx_rental_payments_period on public.rental_payments(period);

-- Rent changes over time (new amount effective from a date)
create table if not exists public.rental_rate_schedules (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    payment_default_id bigint references public.rental_payment_defaults(id) on delete cascade,
    effective_date date not null,
    amount numeric(10,2) not null,
    note text
);

-- Property expenses with receipt photos + labor hours + mileage
create table if not exists public.rental_expenses (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    expense_date date not null,
    property_name text,
    category text,
    amount numeric(10,2) not null,
    vendor text,
    martin_hours numeric(6,2),
    colette_hours numeric(6,2),
    miles numeric(8,2),
    notes text,
    receipt_urls jsonb
);
create index if not exists idx_rental_expenses_date on public.rental_expenses(expense_date);

-- RLS: signed-in users only (same pattern as 002_rls_all_tables.sql)
do $$
declare
  t text;
begin
  foreach t in array array[
    'rental_properties',
    'rental_leases',
    'rental_payment_defaults',
    'rental_payments',
    'rental_rate_schedules',
    'rental_expenses'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "signed-in all" on public.%I', t);
    execute format(
      'create policy "signed-in all" on public.%I for all using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')',
      t
    );
  end loop;
end $$;

-- Storage bucket for new receipt uploads (old receipts keep their old URLs)
insert into storage.buckets (id, name, public)
values ('rental-receipts', 'rental-receipts', true)
on conflict (id) do nothing;

drop policy if exists "signed-in read rental-receipts" on storage.objects;
create policy "signed-in read rental-receipts" on storage.objects
  for select using (bucket_id = 'rental-receipts');
drop policy if exists "signed-in insert rental-receipts" on storage.objects;
create policy "signed-in insert rental-receipts" on storage.objects
  for insert with check (bucket_id = 'rental-receipts' and auth.role() = 'authenticated');
drop policy if exists "signed-in delete rental-receipts" on storage.objects;
create policy "signed-in delete rental-receipts" on storage.objects
  for delete using (bucket_id = 'rental-receipts' and auth.role() = 'authenticated');

-- Called by the Import tab after copying rows with their original ids, so
-- the id counters don't hand out numbers that are already taken.
create or replace function public.rental_fix_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'authenticated' then
    raise exception 'must be signed in';
  end if;
  perform setval(pg_get_serial_sequence('public.rental_properties','id'),       greatest(coalesce((select max(id) from public.rental_properties),0),1));
  perform setval(pg_get_serial_sequence('public.rental_leases','id'),           greatest(coalesce((select max(id) from public.rental_leases),0),1));
  perform setval(pg_get_serial_sequence('public.rental_payment_defaults','id'), greatest(coalesce((select max(id) from public.rental_payment_defaults),0),1));
  perform setval(pg_get_serial_sequence('public.rental_payments','id'),         greatest(coalesce((select max(id) from public.rental_payments),0),1));
  perform setval(pg_get_serial_sequence('public.rental_rate_schedules','id'),   greatest(coalesce((select max(id) from public.rental_rate_schedules),0),1));
  perform setval(pg_get_serial_sequence('public.rental_expenses','id'),         greatest(coalesce((select max(id) from public.rental_expenses),0),1));
end;
$$;
