-- Rentals: move the Rental-Manager tables into the Homestead project.
-- Run once in Supabase → SQL Editor. Safe to re-run.
--
-- Tables get a rental_ prefix so they can't collide with the home expense
-- tables. IDs stay bigint so rentals-migrate.html can copy rows over with
-- their original ids (payments/rate_schedules point at payment_defaults by id).
--
-- After running this, open rentals-migrate.html (signed in) to copy the data
-- and receipt files across. See docs/rentals-migration.md.

-- ============================================================================
-- 1. Tables
-- ============================================================================
create table if not exists public.rental_properties (
  id                bigint generated by default as identity primary key,
  created_at        timestamptz default now(),
  property_name     text not null,
  is_building_level boolean default false,
  status            text default 'active'
);

create table if not exists public.rental_leases (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  -- tenants (up to 4) + the joined display string
  tenant_count       integer,
  tenant_names       text,
  tenant1_name       text, tenant1_email text, tenant1_phone text, tenant1_employer text,
  tenant2_name       text, tenant2_email text, tenant2_phone text, tenant2_employer text,
  tenant3_name       text, tenant3_email text, tenant3_phone text, tenant3_employer text,
  tenant4_name       text, tenant4_email text, tenant4_phone text, tenant4_employer text,
  -- legacy single-tenant columns from the very first version
  tenant_email       text, tenant_phone text, tenant_employer text,
  -- property + dates
  property_address   text not null,
  lease_start        date not null,
  lease_end          date not null,
  lease_type         text not null,          -- month_to_month, 12_month, 24_month
  lease_months       integer,
  -- money
  base_rent          numeric(10,2),
  rent_amount        numeric(10,2) not null,
  security_deposit   numeric(10,2),
  first_month_rent   numeric(10,2),
  last_month_rent    numeric(10,2),
  -- pets
  num_cats           integer default 0,
  cat_fee            numeric(10,2) default 0,
  num_dogs           integer default 0,
  dog_fee            numeric(10,2) default 0,
  notes              text,
  status             text default 'active'   -- active, expired, terminated
);
create index if not exists rental_leases_status_idx on public.rental_leases(status);
create index if not exists rental_leases_dates_idx  on public.rental_leases(lease_start, lease_end);

create table if not exists public.rental_expenses (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  expense_date  date not null,
  property_name text,
  category      text,
  amount        numeric(10,2) not null default 0,
  vendor        text,
  martin_hours  numeric(8,2),
  colette_hours numeric(8,2),
  miles         numeric(8,2),
  notes         text,
  receipt_urls  text[]
);
create index if not exists rental_expenses_date_idx     on public.rental_expenses(expense_date);
create index if not exists rental_expenses_property_idx on public.rental_expenses(property_name);

create table if not exists public.rental_payment_defaults (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  type           text,            -- e.g. rent, mortgage, utility
  label          text,
  property_name  text,
  default_amount numeric(10,2),
  due_day        integer,
  status         text default 'active'
);

create table if not exists public.rental_payments (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  payment_default_id bigint references public.rental_payment_defaults(id) on delete cascade,
  period             text not null,   -- 'YYYY-MM'
  amount_owed        numeric(10,2),
  amount_paid        numeric(10,2),
  date_paid          date
);
create index if not exists rental_payments_period_idx on public.rental_payments(period);

create table if not exists public.rental_rate_schedules (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  payment_default_id bigint references public.rental_payment_defaults(id) on delete cascade,
  effective_date     date not null,
  amount             numeric(10,2) not null,
  note               text
);

-- ============================================================================
-- 2. RLS: signed-in users only (same rule as the rest of the site)
-- ============================================================================
do $$
declare t text;
begin
  foreach t in array array[
    'rental_properties','rental_leases','rental_expenses',
    'rental_payment_defaults','rental_payments','rental_rate_schedules'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "signed-in all" on public.%I', t);
    execute format(
      'create policy "signed-in all" on public.%I for all using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')',
      t);
  end loop;
end $$;

-- ============================================================================
-- 3. Receipt files: public bucket (same as the old app), signed-in writes
-- ============================================================================
insert into storage.buckets (id, name, public)
values ('rental-receipts', 'rental-receipts', true)
on conflict (id) do update set public = true;

drop policy if exists "public read rental-receipts"      on storage.objects;
drop policy if exists "signed-in insert rental-receipts" on storage.objects;
drop policy if exists "signed-in update rental-receipts" on storage.objects;
drop policy if exists "signed-in delete rental-receipts" on storage.objects;
create policy "public read rental-receipts" on storage.objects
  for select using (bucket_id = 'rental-receipts');
create policy "signed-in insert rental-receipts" on storage.objects
  for insert with check (bucket_id = 'rental-receipts' and auth.role() = 'authenticated');
create policy "signed-in update rental-receipts" on storage.objects
  for update using (bucket_id = 'rental-receipts' and auth.role() = 'authenticated');
create policy "signed-in delete rental-receipts" on storage.objects
  for delete using (bucket_id = 'rental-receipts' and auth.role() = 'authenticated');

-- ============================================================================
-- 4. Helper used by rentals-migrate.html after copying rows with their old
--    ids: bump each id counter past the highest copied id.
-- ============================================================================
create or replace function public.rental_reset_sequences()
returns void language plpgsql security definer set search_path = public as $$
declare t text;
begin
  foreach t in array array[
    'rental_properties','rental_leases','rental_expenses',
    'rental_payment_defaults','rental_payments','rental_rate_schedules'
  ] loop
    execute format(
      'select setval(pg_get_serial_sequence(%L, ''id''), coalesce((select max(id) from public.%I), 0) + 1, false)',
      'public.' || t, t);
  end loop;
end $$;
grant execute on function public.rental_reset_sequences() to authenticated;
revoke execute on function public.rental_reset_sequences() from anon;
