-- Rentals: rent payments pulled from Zelle emails.
-- Run once in Supabase → SQL Editor. Safe to re-run.
--
-- The zelle-ingest edge function reads "You received money with Zelle" emails
-- from the connected Gmail account(s), stores one row per email here, and
-- applies the ones it can match to rental_payments. Anything it can't match
-- waits in the Rentals → Payments tab for you to assign.

-- Who each Zelle sender is. payment_default_id = the rent line they pay;
-- ignore = not rent (your own transfers, refunds, etc.).
create table if not exists public.rental_zelle_senders (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  sender_name        text not null unique,          -- as Chase prints it, UPPER CASE
  payment_default_id bigint references public.rental_payment_defaults(id) on delete set null,
  ignore             boolean not null default false
);

-- One row per Zelle email.
create table if not exists public.rental_zelle_payments (
  id                 bigint generated by default as identity primary key,
  created_at         timestamptz default now(),
  gmail_message_id   text not null unique,
  account_email      text,
  sender_name        text not null,
  amount             numeric(10,2) not null,
  sent_on            date,
  transaction_number text,
  memo               text,
  period             text,                          -- 'YYYY-MM' the money is for
  payment_default_id bigint references public.rental_payment_defaults(id) on delete set null,
  status             text not null default 'pending',   -- pending, applied, ignored
  note               text,                          -- why it's pending, or what was done
  applied_payment_id bigint references public.rental_payments(id) on delete set null,
  applied_at         timestamptz
);
create index if not exists rental_zelle_payments_status_idx on public.rental_zelle_payments(status);

-- Your own transfers are never rent.
insert into public.rental_zelle_senders (sender_name, ignore)
values ('COLETTE FRITZLEN', true)
on conflict (sender_name) do nothing;

-- RLS: signed-in users only (same as the other rental_* tables)
do $$
declare t text;
begin
  foreach t in array array['rental_zelle_senders','rental_zelle_payments'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "signed-in all" on public.%I', t);
    execute format(
      'create policy "signed-in all" on public.%I for all using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')',
      t);
  end loop;
end $$;

-- Daily automatic scan at 11:00 UTC (7 AM Eastern), one hour after the
-- family-hub deep scan. Needs pg_cron + pg_net and app.service_role_key,
-- which migration 011 already set up.
create extension if not exists pg_cron;
create extension if not exists pg_net;

do $$
begin
  if exists (select 1 from cron.job where jobname = 'zelle-ingest-daily') then
    perform cron.unschedule('zelle-ingest-daily');
  end if;
end $$;

select cron.schedule(
  'zelle-ingest-daily',
  '0 11 * * *',
  $$
  select net.http_post(
    url := 'https://jzpipxvxrtdhmsdkveog.supabase.co/functions/v1/zelle-ingest',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || current_setting('app.service_role_key', true),
      'Content-Type', 'application/json'
    ),
    body := jsonb_build_object('days_back', 7)
  );
  $$
);
