-- Rentals: full lease PDF, per-property lease options, signed lease files,
-- landlord contact settings. Run once in Supabase → SQL Editor. Safe to re-run.

-- 1. Landlord contact info used on the lease (editable on the New Lease page)
create table if not exists public.rental_settings (
  key        text primary key,
  value      text,
  updated_at timestamptz default now()
);
insert into public.rental_settings (key, value) values
  ('landlord_name',  'Colette Fritzlen'),
  ('landlord_email', 'cfritzlen@gmail.com'),
  ('landlord_phone', '917 428 4252')
on conflict (key) do update set value = excluded.value, updated_at = now();

-- 2. Per-property lease choices (appliances, who handles each utility and
--    maintenance item). Copied onto each lease when it's created.
alter table public.rental_properties add column if not exists lease_options jsonb default '{}'::jsonb;
alter table public.rental_leases     add column if not exists lease_options jsonb default '{}'::jsonb;

-- 3. Files attached to a lease: the generated PDF and the signed copy
create table if not exists public.rental_lease_files (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz default now(),
  lease_id     bigint not null references public.rental_leases(id) on delete cascade,
  kind         text not null default 'signed',     -- signed, generated, other
  file_name    text not null,
  storage_path text not null                       -- path inside the rental-leases bucket
);
create index if not exists rental_lease_files_lease_idx on public.rental_lease_files(lease_id);

do $$
declare t text;
begin
  foreach t in array array['rental_settings','rental_lease_files'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "signed-in all" on public.%I', t);
    execute format(
      'create policy "signed-in all" on public.%I for all using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')',
      t);
  end loop;
end $$;

-- 4. Private bucket for lease PDFs (signed links only, never public)
insert into storage.buckets (id, name, public)
values ('rental-leases', 'rental-leases', false)
on conflict (id) do update set public = false;

drop policy if exists "signed-in read rental-leases"   on storage.objects;
drop policy if exists "signed-in insert rental-leases" on storage.objects;
drop policy if exists "signed-in update rental-leases" on storage.objects;
drop policy if exists "signed-in delete rental-leases" on storage.objects;
create policy "signed-in read rental-leases" on storage.objects
  for select using (bucket_id = 'rental-leases' and auth.role() = 'authenticated');
create policy "signed-in insert rental-leases" on storage.objects
  for insert with check (bucket_id = 'rental-leases' and auth.role() = 'authenticated');
create policy "signed-in update rental-leases" on storage.objects
  for update using (bucket_id = 'rental-leases' and auth.role() = 'authenticated');
create policy "signed-in delete rental-leases" on storage.objects
  for delete using (bucket_id = 'rental-leases' and auth.role() = 'authenticated');
