-- Rentals: in-app lease signing. Run once in Supabase → SQL Editor. Safe to re-run.
--
-- "Send for signature" on a lease creates one row per signer here, each with a
-- private link token. Tenants (and the landlord) open sign.html?t=<token>,
-- draw a signature + initials, and the lease-sign edge function stamps the
-- final PDF once everyone has signed. Tenants never sign in; all their access
-- goes through the edge function, so these tables stay signed-in-only.

alter table public.rental_leases add column if not exists signing_status text default 'draft';   -- draft, sent, signed
alter table public.rental_leases add column if not exists signing_pdf_path text;                 -- the exact PDF that was sent

create table if not exists public.rental_lease_signers (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  lease_id       bigint not null references public.rental_leases(id) on delete cascade,
  role           text not null default 'tenant',        -- tenant, landlord
  name           text not null,
  email          text not null,
  token          uuid not null unique default gen_random_uuid(),
  status         text not null default 'pending',       -- pending, signed
  sent_at        timestamptz,
  viewed_at      timestamptz,
  signed_at      timestamptz,
  signed_ip      text,
  signed_agent   text,
  signature_png  text,                                  -- data URL, drawn by the signer
  initials_png   text
);
create index if not exists rental_lease_signers_lease_idx on public.rental_lease_signers(lease_id);

alter table public.rental_lease_signers enable row level security;
drop policy if exists "signed-in all" on public.rental_lease_signers;
create policy "signed-in all" on public.rental_lease_signers
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
