-- Rentals → Borough tab: East Stroudsburg rental registration paperwork.
-- Run once in Supabase → SQL Editor. Safe to re-run.

-- 1. Per-unit answers for the Borough forms (PIN, meters, yes/no questions…)
alter table public.rental_properties add column if not exists borough_info jsonb default '{}'::jsonb;

-- 2. One row per unit per registration year: where the packet stands
create table if not exists public.rental_borough_filings (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now(),
  year          integer not null,                       -- license year, e.g. 2027
  property_id   bigint not null references public.rental_properties(id) on delete cascade,
  occupancy     text default 'same',                    -- same, new, vacant
  status        text default 'todo',                    -- todo, ready, submitted, licensed
  submitted_on  date,
  notes         text,
  unique (year, property_id)
);

-- 3. Copies of what was sent / the license that came back (rental-leases bucket, borough/…)
create table if not exists public.rental_borough_files (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  filing_id     bigint not null references public.rental_borough_filings(id) on delete cascade,
  kind          text not null default 'sent',           -- sent, license, other
  file_name     text not null,
  storage_path  text not null
);
create index if not exists rental_borough_files_filing_idx on public.rental_borough_files(filing_id);

do $$
declare t text;
begin
  foreach t in array array['rental_borough_filings','rental_borough_files'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "signed-in all" on public.%I', t);
    execute format(
      'create policy "signed-in all" on public.%I for all using (auth.role() = ''authenticated'') with check (auth.role() = ''authenticated'')',
      t);
  end loop;
end $$;
