-- Rentals → Borough tab: tenants sign the Addendum to Lease online, then the
-- packet is emailed to the Borough. Run once in Supabase → SQL Editor after
-- 021_borough_registration.sql. Safe to re-run.

alter table public.rental_borough_filings add column if not exists signing_status   text default 'draft';   -- draft, sent, signed
alter table public.rental_borough_filings add column if not exists signing_pdf_path text;                   -- working Addendum PDF with signatures so far
alter table public.rental_borough_filings add column if not exists auto_submit      boolean default true;   -- email the Borough as soon as everyone signed
alter table public.rental_borough_filings add column if not exists submitted_to     text;                   -- where the packet was emailed

-- One row per person who signs the Addendum (tenants; the landlord signs
-- before it goes out). Tenants never sign in: their private link token is
-- checked by the borough-sign edge function.
create table if not exists public.rental_borough_signers (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz default now(),
  filing_id      bigint not null references public.rental_borough_filings(id) on delete cascade,
  role           text not null default 'tenant',        -- tenant, landlord
  name           text not null,
  email          text not null,
  token          uuid not null unique default gen_random_uuid(),
  tenant_index   integer,                               -- 0-3: which occupant line on the Addendum
  status         text not null default 'pending',       -- pending, signed
  stamped        boolean default false,                 -- already drawn onto signing_pdf_path
  sent_at        timestamptz,
  viewed_at      timestamptz,
  signed_at      timestamptz,
  signed_ip      text,
  signed_agent   text,
  signature_png  text                                   -- data URL drawn by the signer
);
create index if not exists rental_borough_signers_filing_idx on public.rental_borough_signers(filing_id);

alter table public.rental_borough_signers enable row level security;
drop policy if exists "signed-in all" on public.rental_borough_signers;
create policy "signed-in all" on public.rental_borough_signers
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
