-- Rentals → Properties tab: per-building facts (parcel, lender, insurance…)
-- and the paperwork that goes with each building and year (tax bills, escrow
-- analysis, Form 1098, insurance, licenses, deed). Run once in Supabase →
-- SQL Editor. Safe to re-run.

-- 1. Facts about a building live on its building-level rental_properties row
alter table public.rental_properties add column if not exists property_info jsonb default '{}'::jsonb;

-- 2. Documents per building (files in the private rental-leases bucket, property/…)
create table if not exists public.rental_property_docs (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz default now(),
  property_id   bigint not null references public.rental_properties(id) on delete cascade,
  kind          text not null,              -- tax_county, tax_school, escrow, f1098, insurance, license, inspection, deed, lead, other
  year          integer,                    -- tax/statement year (null for one-time documents)
  title         text,
  file_name     text,
  storage_path  text,                       -- may be null for a record without a file (e.g. "paid by escrow")
  amount        numeric(12,2),
  due_on        date,
  paid_on       date,
  notes         text
);
create index if not exists rental_property_docs_property_idx on public.rental_property_docs(property_id);

alter table public.rental_property_docs enable row level security;
drop policy if exists "signed-in all" on public.rental_property_docs;
create policy "signed-in all" on public.rental_property_docs
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
