-- Kids Hub → Color Chart: the daycare-style green / yellow / red behavior
-- chart, with five spots (super green, green-yellow, yellow, orange, red).
-- Every morning starts fresh at super green: a day's level is simply
-- 5 + (approved ups) - (downs), clamped to 1..5, so there is nothing to reset.
-- Run in Supabase → SQL Editor. Safe to re-run.

create table if not exists public.color_chart_kids (
  id             uuid primary key default gen_random_uuid(),
  household_id   uuid references public.households(id) on delete cascade,
  name           text not null,
  pin_hash       text,                                   -- sha256 of the parent PIN (set from the page)
  share_token    uuid not null unique default gen_random_uuid(),  -- teacher's private read-only link
  share_reasons  boolean not null default true,          -- teacher sees the log, not just the color
  created_at     timestamptz not null default now()
);

-- Chores that move up, and reasons for moving down. Editable from the page.
create table if not exists public.color_chart_actions (
  id         bigint generated by default as identity primary key,
  kid_id     uuid not null references public.color_chart_kids(id) on delete cascade,
  kind       text not null check (kind in ('up','down')),
  label      text not null,
  emoji      text,
  weight     integer not null default 1 check (weight between 1 and 4),  -- how many spots it moves
  sort       integer not null default 0,
  active     boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists color_chart_actions_kid_idx on public.color_chart_actions(kid_id);

-- One row per thing that happened. A chore the kid taps is an 'up' with
-- status 'pending' until a parent enters the PIN and approves it.
create table if not exists public.color_chart_events (
  id         bigint generated by default as identity primary key,
  kid_id     uuid not null references public.color_chart_kids(id) on delete cascade,
  day        date not null,                              -- local calendar day, sent by the page
  at         timestamptz not null default now(),
  kind       text not null check (kind in ('up','down')),
  status     text not null default 'approved' check (status in ('pending','approved','denied')),
  label      text not null,
  note       text,
  weight     integer not null default 1 check (weight between 1 and 4),  -- spots moved
  source     text not null default 'home' check (source in ('home','teacher')),
  created_by uuid
);
create index if not exists color_chart_events_kid_day_idx on public.color_chart_events(kid_id, day);

-- Fill household_id from the signed-in member
drop trigger if exists trg_default_household_color_chart on public.color_chart_kids;
create trigger trg_default_household_color_chart
  before insert on public.color_chart_kids
  for each row execute function public.default_household();

-- RLS: household walls (the teacher link is served by the color-chart-share
-- edge function with the service role, so anon needs nothing here). The
-- teacher's own entries land with source = 'teacher'.
alter table public.color_chart_kids    enable row level security;
alter table public.color_chart_actions enable row level security;
alter table public.color_chart_events  enable row level security;

drop policy if exists "household kids" on public.color_chart_kids;
create policy "household kids" on public.color_chart_kids
  for all using (household_id in (select public.my_household_ids()))
  with check (household_id is null or household_id in (select public.my_household_ids()));

drop policy if exists "household actions" on public.color_chart_actions;
create policy "household actions" on public.color_chart_actions
  for all using (kid_id in (select id from public.color_chart_kids where household_id in (select public.my_household_ids())))
  with check (kid_id in (select id from public.color_chart_kids where household_id in (select public.my_household_ids())));

drop policy if exists "household events" on public.color_chart_events;
create policy "household events" on public.color_chart_events
  for all using (kid_id in (select id from public.color_chart_kids where household_id in (select public.my_household_ids())))
  with check (kid_id in (select id from public.color_chart_kids where household_id in (select public.my_household_ids())));
