-- Color Chart: nap unicorns. Five unicorns a week (Mon-Fri); each school
-- day with a nap keeps one. Marked by the teacher from her link or by a
-- grown-up with the PIN. Run in Supabase → SQL Editor. Safe to re-run.

create table if not exists public.color_chart_naps (
  id         bigint generated by default as identity primary key,
  kid_id     uuid not null references public.color_chart_kids(id) on delete cascade,
  day        date not null,
  napped     boolean not null,
  source     text not null default 'home' check (source in ('home','teacher')),
  created_at timestamptz not null default now(),
  unique (kid_id, day)
);

alter table public.color_chart_naps enable row level security;
drop policy if exists "household naps" on public.color_chart_naps;
create policy "household naps" on public.color_chart_naps
  for all using (kid_id in (select id from public.color_chart_kids where household_id in (select public.my_household_ids())))
  with check (kid_id in (select id from public.color_chart_kids where household_id in (select public.my_household_ids())));
